title: Andrew Ortiz
description: Principal Counsultant, ServiceNow Engagement Manager @ Advizex, Inc.
baseurl: "/aortiz-resume/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "andrew@ortiz.io"
linkedin: "https://www.linkedin.com/in/anortiz08"
github: "https://github.com/anortiz08"
website: "http://anortiz08.github.io/"
#medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
